'\nCrypto Market Data Domain.\n'
import pandas as pd
from vnstock_data.ui._registry import MARKET_SOURCES
from vnstock_data.ui.domains.market.base import BaseMarketData
class CryptoMarket(BaseMarketData):
	"\n    Crypto Market Data (Layer 2) – Unified UI interface for cryptocurrency.\n\n    Core methods (inherited from BaseMarketData, shared schema with all asset classes):\n    ──────────────────────────────────────────────────────────────────────────────────\n    ohlcv(interval, limit, mode)   OHLCV bars; mode=None (default, chart-opt) or 'raw'\n    trades(limit, mode)            Time & Sales; mode='raw' (default) or 'aggregate'\n    order_book(limit)              L2 Market Depth (bid/ask levels)\n    quote()                        24-hour rolling quote snapshot\n\n    Extended methods (Crypto-specific, universal naming):\n    ─────────────────────────────────────────────────────\n    trade_history   → GET /api/v3/historicalTrades (older trades by ID)\n    vwap            → GET /api/v3/avgPrice         (volume-weighted avg price)\n    daily_stats     → GET /api/v3/ticker/tradingDay(trading-day session stats)\n    last_price      → GET /api/v3/ticker/price     (last traded price, LTP)\n    rolling_stats   → GET /api/v3/ticker           (rolling-window statistics)\n    reference_price(mode)\n        mode='price' → GET /api/v3/referencePrice\n        mode='calc'  → GET /api/v3/referencePrice/calculation\n    ";session_stats=None;trading_stats=None
	def __init__(B,symbol,**A):super().__init__(symbol=symbol,domain_name=bytes([109,97,114,107,101,116,46,99,114,121,112,116,111]).decode(),layer_sources=MARKET_SOURCES,**A)
	def trades(A,limit=500,mode=bytes([114,97,119]).decode(),**B):"\n        Tick-by-tick trade tape (Time & Sales).\n\n        Args:\n            limit (int): Number of records (default 500, max 1000).\n            mode (str):\n                - ``'raw'`` (default) – individual fills. Binance: ``GET /api/v3/trades``\n                - ``'aggregate'`` – compressed fills (same price & direction merged).\n                  Binance: ``GET /api/v3/aggTrades``\n\n        Returns:\n            pd.DataFrame: Schema ``[time, price, volume, side, match_type, id]``\n        ";return A._dispatch(bytes([116,114,97,100,101,115]).decode(),limit=limit,mode=mode,**B)
	def trade_history(A,**B):'Historical trade look-up by ID. Binance: ``GET /api/v3/historicalTrades``';return A._dispatch(bytes([116,114,97,100,101,95,104,105,115,116,111,114,121]).decode(),**B)
	def vwap(A,**B):'Volume-Weighted Average Price. Binance: ``GET /api/v3/avgPrice``';return A._dispatch(bytes([118,119,97,112]).decode(),**B)
	def daily_stats(A,**B):'Trading-day session statistics. Binance: ``GET /api/v3/ticker/tradingDay``';return A._dispatch(bytes([100,97,105,108,121,95,115,116,97,116,115]).decode(),**B)
	def last_price(A,**B):'Last Traded Price (LTP). Binance: ``GET /api/v3/ticker/price``';return A._dispatch(bytes([108,97,115,116,95,112,114,105,99,101]).decode(),**B)
	def rolling_stats(A,**B):'Rolling-window price-change statistics. Binance: ``GET /api/v3/ticker``';return A._dispatch(bytes([114,111,108,108,105,110,103,95,115,116,97,116,115]).decode(),**B)
	def reference_price(A,mode=bytes([112,114,105,99,101]).decode(),**B):"\n        Reference / indicative price.\n\n        Args:\n            mode (str):\n                - ``'price'`` (default) – reference price. Binance: ``GET /api/v3/referencePrice``\n                - ``'calc'`` – calculation breakdown. Binance: ``GET /api/v3/referencePrice/calculation``\n\n        Note: Returns empty DataFrame if symbol has no reference price.\n        ";return A._dispatch(bytes([114,101,102,101,114,101,110,99,101,95,112,114,105,99,101]).decode(),mode=mode,**B)