from datetime import datetime
import pandas as pd,requests
from vnai import agg_execution
from vnstock.core.utils.logger import get_logger
from vnstock_data.core.utils.user_agent import get_headers
from vnstock_data.explorer.vnd.const import _INSIGHT_BASE,_TOP_STOCK_COLS,_TOP_STOCK_INDEX
logger=get_logger(__name__)
class TopStock:
	"\n    Lớp để lấy dữ liệu cổ phiếu hàng đầu từ API VND.\n\n    Lớp này cung cấp các phương thức để truy xuất dữ liệu về top 10 cổ phiếu\n    dựa trên các tiêu chí hiệu suất khác nhau như tăng giá, giảm giá,\n    giá trị giao dịch, khối lượng đột biến, giao dịch thỏa thuận đột biến,\n    và mua/bán của nhà đầu tư nước ngoài.\n\n    Thuộc tính:\n    -----------\n    base_url : str\n        URL cơ sở cho API VND.\n    headers : dict\n        Headers HTTP được sử dụng trong các yêu cầu API, bao gồm user-agent.\n    data_source : str\n        Tên nguồn dữ liệu, trong trường hợp này là 'VND'.\n\n    Phương thức:\n    -----------\n    gainer(index: str='VNINDEX', limit: int=10) -> pd.DataFrame:\n        Lấy top 10 cổ phiếu có tỷ lệ tăng giá cao nhất cho chỉ số cụ thể.\n    \n    loser(index: str='VNINDEX', limit: int=10) -> pd.DataFrame:\n        Lấy top 10 cổ phiếu có tỷ lệ giảm giá cao nhất cho chỉ số cụ thể.\n    \n    trade(index: str='VNINDEX', limit: int=10) -> pd.DataFrame:\n        Lấy top 10 cổ phiếu có giá trị giao dịch lớn nhất cho chỉ số cụ thể.\n    \n    volume(index: str='VNINDEX', limit: int=10) -> pd.DataFrame:\n        Lấy top 10 cổ phiếu có khối lượng đột biến lớn nhất cho chỉ số cụ thể.\n    \n    deal(index: str='VNINDEX', limit: int=10) -> pd.DataFrame:\n        Lấy top 10 cổ phiếu có giao dịch thỏa thuận đột biến lớn nhất cho chỉ số cụ thể.\n\n    top_foreign_buy(trading_date: str, limit: int=10) -> pd.DataFrame:\n        Lấy top 10 cổ phiếu có giá trị mua ròng lớn nhất từ nhà đầu tư nước ngoài.\n\n    top_foreign_trade(trading_date: str, limit: int=10) -> pd.DataFrame:\n        Lấy top 10 cổ phiếu có giá trị giao dịch ròng lớn nhất từ nhà đầu tư nước ngoài.\n    "
	def __init__(A,show_log=False,random_agent=False):
		'\n        Khởi tạo lớp TopStock với tùy chọn sử dụng user-agent ngẫu nhiên và hiển thị log.\n\n        Tham số:\n        -----------\n        show_log : bool, tùy chọn\n            Nếu True, hiển thị thông báo log.\n        random_agent : bool, tùy chọn\n            Nếu True, sử dụng user-agent ngẫu nhiên trong headers HTTP (mặc định là False).\n        ';B=show_log;A.show_log=B;A.base_url=_INSIGHT_BASE;A.headers=get_headers(data_source=bytes([86,78,68]).decode(),random_agent=random_agent);A.data_source=bytes([86,78,68]).decode()
		if not B:logger.setLevel(bytes([67,82,73,84,73,67,65,76]).decode())
	def _fetch_data(A,url):
		'\n        Phương thức nội bộ để lấy dữ liệu từ URL đã cho và trả về dưới dạng DataFrame của pandas.\n\n        Tham số:\n        -----------\n        url : str\n            URL để gửi yêu cầu GET.\n\n        Trả về:\n        --------\n        pd.DataFrame\n            Một DataFrame chứa dữ liệu lấy từ API, hoặc một DataFrame trống nếu có lỗi xảy ra.\n        '
		try:
			if A.show_log:logger.info(f"Lấy dữ liệu từ URL: {url}")
			B=requests.get(url,headers=A.headers);B.raise_for_status();C=B.json()
			if bytes([100,97,116,97]).decode()in C:D=pd.DataFrame(C[bytes([100,97,116,97]).decode()]);D.rename(columns=_TOP_STOCK_COLS,inplace=True);return D
			else:logger.error(bytes([75,104,195,180,110,103,32,99,195,179,32,116,114,198,176,225,187,157,110,103,32,39,100,97,116,97,39,32,116,114,111,110,103,32,112,104,225,186,163,110,32,104,225,187,147,105,32,74,83,79,78]).decode());return pd.DataFrame()
		except requests.exceptions.RequestException as E:logger.error(f"Lỗi khi lấy dữ liệu: {E}");return pd.DataFrame()
	def _fetch_foreign_data(A,url):
		"\n        Phương thức nội bộ để lấy dữ liệu giao dịch nước ngoài từ URL đã cho và trả về dưới dạng DataFrame.\n\n        Tham số:\n        -----------\n        url : str\n            URL để gửi yêu cầu GET.\n\n        Trả về:\n        --------\n        pd.DataFrame\n            Một DataFrame chứa dữ liệu giao dịch nước ngoài, với các cột được đổi tên thành 'symbol', 'date', và 'net_value'.\n        "
		try:
			if A.show_log:logger.info(f"Lấy dữ liệu từ URL: {url}")
			B=requests.get(url,headers=A.headers);B.raise_for_status();C=B.json()
			if bytes([100,97,116,97]).decode()in C:D=pd.DataFrame(C[bytes([100,97,116,97]).decode()]);D.rename(columns={bytes([99,111,100,101]).decode():bytes([115,121,109,98,111,108]).decode(),bytes([116,114,97,100,105,110,103,68,97,116,101]).decode():bytes([100,97,116,101]).decode(),bytes([110,101,116,86,97,108]).decode():bytes([110,101,116,95,118,97,108,117,101]).decode()},inplace=True);return D
			else:logger.error(bytes([75,104,195,180,110,103,32,99,195,179,32,116,114,198,176,225,187,157,110,103,32,39,100,97,116,97,39,32,116,114,111,110,103,32,112,104,225,186,163,110,32,104,225,187,147,105,32,74,83,79,78]).decode());return pd.DataFrame()
		except requests.exceptions.RequestException as E:logger.error(f"Lỗi khi lấy dữ liệu: {E}");return pd.DataFrame()
	def _get_index_code(A,index):"\n        Phương thức nội bộ để lấy mã chỉ số từ tên chỉ số.\n\n        Tham số:\n        -----------\n        index : str\n            Tên chỉ số được người dùng cung cấp (ví dụ: 'VNINDEX').\n\n        Trả về:\n        --------\n        str\n            Mã chỉ số tương ứng (ví dụ: 'VNIndex').\n        ";return _TOP_STOCK_INDEX.get(index.upper(),bytes([86,78,73,110,100,101,120]).decode())
	@agg_execution(bytes([86,78,68,46,101,120,116]).decode())
	def gainer(self,index=bytes([86,78,73,78,68,69,88]).decode(),limit=10):"\n        Lấy top 10 cổ phiếu có tỷ lệ tăng giá cao nhất cho chỉ số cụ thể.\n\n        Tham số:\n        -----------\n        index : str, tùy chọn\n            Tên chỉ số (mặc định là 'VNINDEX').\n        limit : int, tùy chọn\n            Số lượng cổ phiếu muốn lấy (mặc định là 10).\n\n        Trả về:\n        --------\n        pd.DataFrame\n            Một DataFrame chứa top cổ phiếu tăng giá.\n        ";A=self;B=A._get_index_code(index);C=f"{A.base_url}/top_stocks?q=index:{B}~nmVolumeAvgCr20D:gte:10000~priceChgPctCr1D:gt:0&size={limit}&sort=priceChgPctCr1D";return A._fetch_data(C)
	@agg_execution(bytes([86,78,68,46,101,120,116]).decode())
	def loser(self,index=bytes([86,78,73,78,68,69,88]).decode(),limit=10):"\n        Lấy top 10 cổ phiếu có tỷ lệ giảm giá cao nhất cho chỉ số cụ thể.\n\n        Tham số:\n        -----------\n        index : str, tùy chọn\n            Tên chỉ số (mặc định là 'VNINDEX').\n        limit : int, tùy chọn\n            Số lượng cổ phiếu muốn lấy (mặc định là 10).\n\n        Trả về:\n        --------\n        pd.DataFrame\n            Một DataFrame chứa top cổ phiếu giảm giá.\n        ";A=self;B=A._get_index_code(index);C=f"{A.base_url}/top_stocks?q=index:{B}~nmVolumeAvgCr20D:gte:10000~priceChgPctCr1D:lt:0&size={limit}&sort=priceChgPctCr1D:asc";return A._fetch_data(C)
	@agg_execution(bytes([86,78,68,46,101,120,116]).decode())
	def value(self,index=bytes([86,78,73,78,68,69,88]).decode(),limit=10):"\n        Lấy top 10 cổ phiếu có giá trị giao dịch lớn nhất cho chỉ số cụ thể.\n\n        Tham số:\n        -----------\n        index : str, tùy chọn\n            Tên chỉ số (mặc định là 'VNINDEX').\n        limit : int, tùy chọn\n            Số lượng cổ phiếu muốn lấy (mặc định là 10).\n\n        Trả về:\n        --------\n        pd.DataFrame\n            Một DataFrame chứa top cổ phiếu có giá trị giao dịch lớn nhất.\n        ";A=self;B=A._get_index_code(index);C=f"{A.base_url}/top_stocks?q=index:{B}~accumulatedVal:gt:0&size={limit}&sort=accumulatedVal";return A._fetch_data(C)
	@agg_execution(bytes([86,78,68,46,101,120,116]).decode())
	def volume(self,index=bytes([86,78,73,78,68,69,88]).decode(),limit=10):"\n        Lấy top 10 cổ phiếu có khối lượng đột biến lớn nhất cho chỉ số cụ thể.\n\n        Tham số:\n        -----------\n        index : str, tùy chọn\n            Tên chỉ số (mặc định là 'VNINDEX').\n        limit : int, tùy chọn\n            Số lượng cổ phiếu muốn lấy (mặc định là 10).\n\n        Trả về:\n        --------\n        pd.DataFrame\n            Một DataFrame chứa top cổ phiếu có khối lượng đột biến lớn nhất.\n        ";A=self;B=A._get_index_code(index);C=f"{A.base_url}/top_stocks?q=index:{B}~nmVolumeAvgCr20D:gte:10000~nmVolNmVolAvg20DPctCr:gte:100&size={limit}&sort=nmVolNmVolAvg20DPctCr";return A._fetch_data(C)
	@agg_execution(bytes([86,78,68,46,101,120,116]).decode())
	def deal(self,index=bytes([86,78,73,78,68,69,88]).decode(),limit=10):"\n        Lấy top 10 cổ phiếu có giao dịch thỏa thuận đột biến lớn nhất cho chỉ số cụ thể.\n\n        Tham số:\n        -----------\n        index : str, tùy chọn\n            Tên chỉ số (mặc định là 'VNINDEX').\n        limit : int, tùy chọn\n            Số lượng cổ phiếu muốn lấy (mặc định là 10).\n\n        Trả về:\n        --------\n        pd.DataFrame\n            Một DataFrame chứa top cổ phiếu có giao dịch thỏa thuận đột biến lớn nhất.\n        ";A=self;B=A._get_index_code(index);C=f"{A.base_url}/top_stocks?size={limit}&q=index:{B}~nmVolumeAvgCr20D:gte:10000&sort=ptVolTotalVolAvg20DPctCr";return A._fetch_data(C)
	@agg_execution(bytes([86,78,68,46,101,120,116]).decode())
	def foreign_buy(self,date=None,limit=10):
		"\n        Lấy top 10 cổ phiếu có giá trị mua ròng lớn nhất từ nhà đầu tư nước ngoài.\n\n        Tham số:\n        -----------\n        date : str\n            Ngày giao dịch dưới dạng 'YYYY-mm-dd'. Ví dụ: '2024-08-16'.\n        limit : int, tùy chọn\n            Số lượng cổ phiếu muốn lấy (mặc định là 10).\n\n        Trả về:\n        --------\n        pd.DataFrame\n            Một DataFrame chứa top cổ phiếu có giá trị mua ròng lớn nhất từ nhà đầu tư nước ngoài.\n        ";A=date
		if A is None:A=datetime.now().strftime(bytes([37,89,45,37,109,45,37,100]).decode())
		B=f"https://api-finfo.vndirect.com.vn/v4/foreigns?q=type:STOCK,IFC,ETF~netVal:gt:0~tradingDate:{A}&sort=tradingDate~netVal:desc&size={limit}&fields=code,netVal,tradingDate";return self._fetch_foreign_data(B)
	@agg_execution(bytes([86,78,68,46,101,120,116]).decode())
	def foreign_sell(self,date=None,limit=10):
		"\n        Lấy top 10 cổ phiếu có giá trị giao dịch ròng lớn nhất từ nhà đầu tư nước ngoài.\n\n        Tham số:\n        -----------\n        date : str\n            Ngày giao dịch dưới dạng 'YYYY-mm-dd'. Ví dụ: '2024-08-16'.\n        limit : int, tùy chọn\n            Số lượng cổ phiếu muốn lấy (mặc định là 10).\n\n        Trả về:\n        --------\n        pd.DataFrame\n            Một DataFrame chứa top cổ phiếu có giá trị giao dịch ròng lớn nhất từ nhà đầu tư nước ngoài.\n        ";A=date
		if A is None:A=datetime.now().strftime(bytes([37,89,45,37,109,45,37,100]).decode())
		B=f"https://api-finfo.vndirect.com.vn/v4/foreigns?q=type:STOCK,IFC,ETF~netVal:lt:0~tradingDate:{A}&sort=tradingDate~netVal:asc&size={limit}&fields=code,netVal,tradingDate";return self._fetch_foreign_data(B)
from vnstock_data.core.registry import ProviderRegistry
ProviderRegistry.register(bytes([105,110,115,105,103,104,116]).decode(),bytes([118,110,100]).decode(),TopStock)