"""
Phase 4: LightGBM Propensity-to-Buy Model

Train a binary classifier on (symbol, date) feature rows generated by Phase 2,
using labels from Phase 3. Outputs a trained model + feature importance + eval metrics.

Usage:
    python -m pipeline.phase4_ml_model               # train + evaluate
    python -m pipeline.phase4_ml_model --check        # print dataset stats
    python -m pipeline.phase4_ml_model --predict DATE # score today / any date
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import pickle
import sys
import warnings
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore", category=UserWarning)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

# ── paths ──────────────────────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
LABELS_DIR = ROOT / "data" / "labels"
FEATURES_DIR = ROOT / "data" / "features"
MODELS_DIR = ROOT / "data" / "models"
MODELS_DIR.mkdir(parents=True, exist_ok=True)

MODEL_PATH = MODELS_DIR / "lgbm_model.pkl"
METRICS_PATH = MODELS_DIR / "eval_metrics.json"
IMPORTANCE_PATH = MODELS_DIR / "feature_importance.csv"

# ── time split boundaries ──────────────────────────────────────────────────────
TRAIN_START = "2022-07-01"
TRAIN_END   = "2024-06-30"
VAL_START   = "2024-07-01"
VAL_END     = "2024-12-31"
TEST_START  = "2025-01-01"
TEST_END    = "2099-12-31"

# ── features to always drop before training ────────────────────────────────────
DROP_COLS = {
    "close_vnd",
    "avg_val_21d_b",
    "hardcheck_reasons",
    "label_valid",
    "forward_ret_10d",
    "max_drawdown_10d",
    "label",
}

# Raw price levels and any object cols are also dropped dynamically in get_feature_cols().

# ── LightGBM default params ────────────────────────────────────────────────────
LGBM_PARAMS = {
    "objective": "binary",
    "metric": "auc",
    "n_estimators": 500,
    "learning_rate": 0.05,
    "max_depth": 6,
    "num_leaves": 31,
    "min_child_samples": 20,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "reg_alpha": 0.1,
    "reg_lambda": 0.1,
    "random_state": 42,
    "n_jobs": -1,
    "verbose": -1,
}

EARLY_STOPPING_ROUNDS = 50


# ── interaction features ───────────────────────────────────────────────────────

def _add_interaction_features(df: pd.DataFrame) -> pd.DataFrame:
    """Add derived interaction features (non-leaking ratios / products)."""
    out = df.copy()

    if "rsi_14" in out.columns and "mfi_14" in out.columns:
        out["rsi_mfi_gap"] = out["rsi_14"] - out["mfi_14"]

    if "ha_trend" in out.columns and "adx" in out.columns:
        out["trend_adx_interaction"] = out["ha_trend"] * out["adx"]

    if "beta_12m" in out.columns and "asymmetry" in out.columns:
        denom = out["beta_12m"].abs().replace(0, np.nan)
        out["beta_asym_ratio"] = out["asymmetry"] / denom

    if "sharpe_12m" in out.columns and "alpha_3m" in out.columns:
        out["sharpe_alpha"] = out["sharpe_12m"] * out["alpha_3m"]

    return out


# ── dataset helpers ────────────────────────────────────────────────────────────

def get_feature_cols(df: pd.DataFrame, include_fundamentals: bool = False) -> List[str]:
    """Return columns to use as model features (exclude targets, ids, objects)."""
    exclude = set(DROP_COLS)
    # also drop any remaining object / string columns
    obj_cols = set(df.select_dtypes(include="object").columns)
    exclude |= obj_cols
    if not include_fundamentals:
        exclude |= {c for c in df.columns if c.startswith("fund_")}
    return [c for c in df.columns if c not in exclude]


def prepare_dataset() -> pd.DataFrame:
    """
    Load training_set.parquet (Phase 3 output), add interaction features,
    and return a clean DataFrame with MultiIndex (symbol, date).

    Only rows with label_valid==1 are kept.
    """
    ts_path = LABELS_DIR / "training_set.parquet"
    if not ts_path.exists():
        raise FileNotFoundError(
            f"training_set.parquet not found at {ts_path}. "
            "Run Phase 3 first: python -m pipeline.phase3_label_generator"
        )

    df = pd.read_parquet(ts_path)

    # Filter to valid labels only
    if "label_valid" in df.columns:
        before = len(df)
        df = df[df["label_valid"] == 1].copy()
        log.info("Dropped %d rows with label_valid=0 (kept %d)", before - len(df), len(df))

    if "label" not in df.columns:
        raise ValueError("training_set.parquet is missing 'label' column")

    df = _add_interaction_features(df)
    log.info("Dataset shape after interaction features: %s", df.shape)
    return df


def time_split(df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Split by date index level into train / val / test."""
    if isinstance(df.index, pd.MultiIndex):
        dates = df.index.get_level_values("date")
    else:
        dates = pd.to_datetime(df.index)

    train_mask = (dates >= TRAIN_START) & (dates <= TRAIN_END)
    val_mask   = (dates >= VAL_START)   & (dates <= VAL_END)
    test_mask  = (dates >= TEST_START)  & (dates <= TEST_END)

    train = df[train_mask]
    val   = df[val_mask]
    test  = df[test_mask]

    log.info(
        "Split → train=%d  val=%d  test=%d  (total_valid=%d)",
        len(train), len(val), len(test), len(df),
    )
    return train, val, test


# ── training ───────────────────────────────────────────────────────────────────

def _compute_scale_pos_weight(labels: pd.Series) -> float:
    neg = (labels == 0).sum()
    pos = (labels == 1).sum()
    if pos == 0:
        return 1.0
    return round(neg / pos, 4)


def train(df: pd.DataFrame) -> Tuple:
    """
    Train LightGBM with time-based train/val split.
    Returns (booster, feature_cols, metrics_dict).
    """
    try:
        import lightgbm as lgb
    except ImportError as e:
        raise ImportError("lightgbm not installed. Run: pip install lightgbm") from e

    train_df, val_df, test_df = time_split(df)

    # Fall back: if boundaries don't match (e.g. only recent data), use chronological split
    if len(train_df) == 0 or len(val_df) == 0:
        log.warning(
            "Standard train/val split yielded empty sets — using 70/15/15 chronological split."
        )
        n = len(df)
        train_df = df.iloc[: int(n * 0.70)]
        val_df   = df.iloc[int(n * 0.70) : int(n * 0.85)]
        test_df  = df.iloc[int(n * 0.85) :]
        log.info("Fallback split → train=%d  val=%d  test=%d", len(train_df), len(val_df), len(test_df))

    feat_cols = get_feature_cols(df)
    log.info("Feature count: %d", len(feat_cols))

    X_train, y_train = train_df[feat_cols], train_df["label"]
    X_val,   y_val   = val_df[feat_cols],   val_df["label"]
    X_test,  y_test  = test_df[feat_cols],  test_df["label"]

    spw = _compute_scale_pos_weight(y_train)
    log.info(
        "Class balance → train pos=%d neg=%d  scale_pos_weight=%.2f",
        (y_train == 1).sum(), (y_train == 0).sum(), spw,
    )

    params = dict(LGBM_PARAMS)
    params["scale_pos_weight"] = spw

    model = lgb.LGBMClassifier(**params)
    model.fit(
        X_train,
        y_train,
        eval_set=[(X_val, y_val)],
        callbacks=[
            lgb.early_stopping(EARLY_STOPPING_ROUNDS, verbose=False),
            lgb.log_evaluation(period=50),
        ],
    )

    metrics = evaluate(model, feat_cols, train_df, val_df, test_df)
    return model, feat_cols, metrics


# ── evaluation ────────────────────────────────────────────────────────────────

def _roc_auc(y_true, y_prob) -> float:
    from sklearn.metrics import roc_auc_score
    if len(np.unique(y_true)) < 2:
        return float("nan")
    return round(float(roc_auc_score(y_true, y_prob)), 4)


def _pr_auc(y_true, y_prob) -> float:
    from sklearn.metrics import average_precision_score
    if len(np.unique(y_true)) < 2:
        return float("nan")
    return round(float(average_precision_score(y_true, y_prob)), 4)


def _precision_at_k(y_true, y_prob, k: int = 50) -> float:
    """Precision among top-K predictions by probability."""
    if len(y_true) < k:
        k = len(y_true)
    top_k_idx = np.argsort(y_prob)[::-1][:k]
    return round(float(np.mean(y_true.values[top_k_idx])), 4)


def evaluate(model, feat_cols, train_df, val_df, test_df) -> Dict:
    """Compute AUC, PR-AUC, and Precision@50 for each split."""
    results = {}
    for name, split_df in [("train", train_df), ("val", val_df), ("test", test_df)]:
        if len(split_df) == 0:
            results[name] = {}
            continue
        X = split_df[feat_cols]
        y = split_df["label"]
        proba = model.predict_proba(X)[:, 1]
        results[name] = {
            "roc_auc":         _roc_auc(y, proba),
            "pr_auc":          _pr_auc(y, proba),
            "precision_at_50": _precision_at_k(y, proba, k=50),
            "n_rows":          len(split_df),
            "n_pos":           int((y == 1).sum()),
        }
    return results


# ── persist ────────────────────────────────────────────────────────────────────

def save_model(model, feat_cols: List[str], metrics: Dict) -> None:
    payload = {
        "model":      model,
        "feat_cols":  feat_cols,
        "train_end":  TRAIN_END,
    }
    with open(MODEL_PATH, "wb") as f:
        pickle.dump(payload, f)
    log.info("Model saved → %s", MODEL_PATH)

    with open(METRICS_PATH, "w") as f:
        json.dump(metrics, f, indent=2)
    log.info("Metrics saved → %s", METRICS_PATH)

    # Feature importance
    import lightgbm as lgb
    fi = pd.DataFrame({
        "feature":    feat_cols,
        "importance": model.feature_importances_,
    }).sort_values("importance", ascending=False)
    fi.to_csv(IMPORTANCE_PATH, index=False)
    log.info("Feature importance saved → %s", IMPORTANCE_PATH)

    # Print top-20
    log.info("\nTop-20 features:\n%s", fi.head(20).to_string(index=False))


def load_model() -> Tuple:
    """Returns (model, feat_cols)."""
    if not MODEL_PATH.exists():
        raise FileNotFoundError(f"No trained model at {MODEL_PATH}. Run training first.")
    with open(MODEL_PATH, "rb") as f:
        payload = pickle.load(f)
    return payload["model"], payload["feat_cols"]


# ── scoring ────────────────────────────────────────────────────────────────────

def predict_scores(
    model,
    feat_cols: List[str],
    feature_df: pd.DataFrame,
    regime_score: Optional[float] = None,
    top_n: int = 200,
) -> pd.DataFrame:
    """
    Score symbols for a given date.

    Args:
        model:         trained LGBMClassifier
        feat_cols:     feature columns used during training
        feature_df:    Phase-2 feature DataFrame (symbol × features for one date)
        regime_score:  optional 0–1 market regime multiplier (from market_regime module)
        top_n:         rank top N symbols (1=best)

    Returns:
        DataFrame with columns [symbol, raw_prob, regime_adj_prob, score_1000, hardcheck_pass]
    """
    df = feature_df.copy()

    # Add interaction features so column set matches training
    df = _add_interaction_features(df)

    # Align columns — fill missing with 0 (graceful degradation)
    missing = [c for c in feat_cols if c not in df.columns]
    if missing:
        log.warning("Missing %d feature cols (filling 0): %s", len(missing), missing[:5])
    for c in missing:
        df[c] = 0.0

    X = df[feat_cols]
    proba = model.predict_proba(X)[:, 1]

    result = pd.DataFrame({
        "symbol":   df.index.get_level_values("symbol") if isinstance(df.index, pd.MultiIndex) else df.index,
        "raw_prob": proba,
    }).reset_index(drop=True)

    # Apply hardcheck mask if present
    if "hardcheck_pass" in df.columns:
        result["hardcheck_pass"] = df["hardcheck_pass"].values
    else:
        result["hardcheck_pass"] = True

    # Regime adjustment
    multiplier = float(regime_score) if regime_score is not None else 1.0
    result["regime_adj_prob"] = (result["raw_prob"] * multiplier).clip(0, 1)

    # Rank and scale to 1–1000
    result = result.sort_values("regime_adj_prob", ascending=False).reset_index(drop=True)
    n = min(top_n, len(result))
    result["rank"] = range(1, len(result) + 1)

    # Score 1000 → 1 (best = 1000, worst = 1)
    if n > 1:
        result["score_1000"] = (
            1000 - (result["rank"] - 1) * (999 / (n - 1))
        ).round(0).astype(int).clip(1, 1000)
    else:
        result["score_1000"] = 1000

    # Zero-out failed hardcheck symbols
    result.loc[~result["hardcheck_pass"].astype(bool), "score_1000"] = 0

    return result[["symbol", "raw_prob", "regime_adj_prob", "score_1000", "hardcheck_pass", "rank"]]


# ── Tier 3: technical confirmation filter ──────────────────────────────────────

PROB_CUTOFF = 0.58          # recalibrated 2026-05-17: 12m test WR=57.5%, ~3/day [5d/3% label, max_prob=0.656]
EMA_NEAR_PCT = 5.0          # max % deviation from EMA9 or EMA26 to be "near"

def tier3_filter(
    scores: pd.DataFrame,
    feature_df: pd.DataFrame,
    prob_cutoff: float = PROB_CUTOFF,
) -> pd.DataFrame:
    """
    Apply Tier 3 technical confirmation to scored symbols.

    Conditions (all three must pass):
      T1: raw_prob >= prob_cutoff  (model confidence threshold)
      T2: volume today >= 80% of 20-day avg  (vol_ratio_20d >= 0.80)
      T3: close within ±EMA_NEAR_PCT% of EMA9 OR EMA26  (entry zone)
      T4: no bearish reversal candles  (no shooting_star / bearish_engulfing / evening_star)

    Args:
        scores:      output of predict_scores() — must include symbol, raw_prob, hardcheck_pass
        feature_df:  Phase-2 feature DataFrame for the same date
        prob_cutoff: minimum raw_prob to consider

    Returns:
        DataFrame of symbols passing all tiers, with tier3_pass and tier3_reasons columns.
        Sorted by raw_prob descending.
    """
    fdf = feature_df.copy()

    # Merge scores with features on symbol
    merged = scores[scores["hardcheck_pass"].astype(bool)].copy()
    merged = merged.set_index("symbol")
    fdf.index.name = "symbol"

    for col in ["vol_ratio_20d", "ema9", "ema26", "close_vnd",
                "candle_shooting_star", "candle_bearish_engulfing", "candle_evening_star"]:
        if col in fdf.columns:
            merged[col] = fdf[col]
        else:
            merged[col] = np.nan

    merged = merged.reset_index()
    results = []

    for _, row in merged.iterrows():
        failures = []

        # T1: probability cut-off
        if row["raw_prob"] < prob_cutoff:
            failures.append(f"T1:prob_low({row['raw_prob']:.3f}<{prob_cutoff})")

        # T2: volume confirmation
        vr = row.get("vol_ratio_20d", np.nan)
        if np.isfinite(vr) and vr < 0.80:
            failures.append(f"T2:vol_weak({vr:.2f}x)")

        # T3: price near EMA9 or EMA26
        close = row.get("close_vnd", np.nan)
        ema9  = row.get("ema9",  np.nan)
        ema26 = row.get("ema26", np.nan)
        near_ema9  = np.isfinite(ema9)  and abs(close / ema9  - 1) * 100 <= EMA_NEAR_PCT
        near_ema26 = np.isfinite(ema26) and abs(close / ema26 - 1) * 100 <= EMA_NEAR_PCT
        if np.isfinite(close) and not (near_ema9 or near_ema26):
            pct9  = abs(close / ema9  - 1) * 100 if np.isfinite(ema9)  else 999
            pct26 = abs(close / ema26 - 1) * 100 if np.isfinite(ema26) else 999
            failures.append(f"T3:not_near_ema(ema9={pct9:.1f}% ema26={pct26:.1f}%)")

        # T4: no bearish reversal candles
        bearish_candles = {
            "candle_shooting_star":     "T4:shooting_star",
            "candle_bearish_engulfing": "T4:bearish_engulfing",
            "candle_evening_star":      "T4:evening_star",
        }
        for col, tag in bearish_candles.items():
            if row.get(col, 0.0) == 1.0:
                failures.append(tag)

        results.append({
            "symbol":        row["symbol"],
            "raw_prob":      round(row["raw_prob"], 4),
            "score_1000":    row["score_1000"],
            "rank":          row["rank"],
            "tier3_pass":    len(failures) == 0,
            "tier3_reasons": "|".join(failures) if failures else "",
        })

    df_out = pd.DataFrame(results).sort_values("raw_prob", ascending=False).reset_index(drop=True)
    return df_out


def daily_shortlist(
    feature_df: pd.DataFrame,
    model,
    feat_cols: List[str],
    prob_cutoff: float = PROB_CUTOFF,
    regime_score: Optional[float] = None,
) -> pd.DataFrame:
    """
    Full pipeline: score all symbols → hardcheck → Tier 3 → sorted shortlist.
    Returns only symbols passing all tiers.
    """
    scores = predict_scores(model, feat_cols, feature_df, regime_score=regime_score)
    t3 = tier3_filter(scores, feature_df, prob_cutoff=prob_cutoff)
    passed = t3[t3["tier3_pass"]].copy()
    return passed


# ── CLI entry points ───────────────────────────────────────────────────────────

def show_stats() -> None:
    """Print dataset and model statistics."""
    ts_path = LABELS_DIR / "training_set.parquet"
    if not ts_path.exists():
        print("training_set.parquet not found. Run Phase 3 first.")
        return

    df = pd.read_parquet(ts_path)
    print(f"\n{'='*60}")
    print("PHASE 4 — DATASET STATS")
    print(f"{'='*60}")
    print(f"Total rows:      {len(df)}")

    if "label_valid" in df.columns:
        valid = df[df["label_valid"] == 1]
        print(f"Valid rows:      {len(valid)}")
        if "label" in valid.columns:
            vc = valid["label"].value_counts()
            pos = vc.get(1, 0)
            neg = vc.get(0, 0)
            total = pos + neg
            if total > 0:
                print(f"Positive (buy):  {pos}  ({pos/total*100:.1f}%)")
                print(f"Negative:        {neg}  ({neg/total*100:.1f}%)")
                spw = neg / pos if pos > 0 else 1
                print(f"scale_pos_weight (neg/pos): {spw:.2f}")
            else:
                print("No labeled rows yet — run Phase 2 backfill + Phase 3.")

    if isinstance(df.index, pd.MultiIndex):
        dates = df.index.get_level_values("date")
        syms  = df.index.get_level_values("symbol")
        print(f"Date range:      {dates.min().date()} → {dates.max().date()}")
        print(f"Symbols:         {syms.nunique()}")

    feat_cols = get_feature_cols(df)
    df_int = _add_interaction_features(df)
    feat_cols_int = get_feature_cols(df_int)
    print(f"Feature cols:    {len(feat_cols)} base + {len(feat_cols_int)-len(feat_cols)} interaction = {len(feat_cols_int)} total")

    if MODEL_PATH.exists():
        print(f"\nTrained model:   {MODEL_PATH}")
        if METRICS_PATH.exists():
            m = json.load(open(METRICS_PATH))
            for split, vals in m.items():
                if vals:
                    print(f"  [{split}] AUC={vals.get('roc_auc','?')}  PR-AUC={vals.get('pr_auc','?')}  P@50={vals.get('precision_at_50','?')}  n={vals.get('n_rows','?')}")
    else:
        print("\nNo trained model yet.")
    print()


def run() -> None:
    """Full train + save pipeline."""
    log.info("=== Phase 4: LightGBM Training ===")
    df = prepare_dataset()

    if len(df) < 50:
        log.warning(
            "Only %d valid rows — model may not be meaningful. "
            "Run Phase 1A backfill + Phase 2 backfill + Phase 3 to get more data.",
            len(df),
        )

    model, feat_cols, metrics = train(df)

    log.info("\n--- Evaluation Results ---")
    for split, vals in metrics.items():
        if vals:
            log.info(
                "[%s] ROC-AUC=%.4f  PR-AUC=%.4f  P@50=%.4f  n=%d  pos=%d",
                split,
                vals.get("roc_auc", float("nan")),
                vals.get("pr_auc", float("nan")),
                vals.get("precision_at_50", float("nan")),
                vals.get("n_rows", 0),
                vals.get("n_pos", 0),
            )

    save_model(model, feat_cols, metrics)
    log.info("=== Phase 4 complete ===")


def run_predict(date_str: str, prob_cutoff: float = PROB_CUTOFF) -> None:
    """Score all symbols for a specific date, apply Tier 3, print shortlist."""
    model, feat_cols = load_model()

    feat_path = FEATURES_DIR / f"{date_str}.parquet"
    if not feat_path.exists():
        log.error("No feature file for %s. Run Phase 2 for that date first.", date_str)
        sys.exit(1)

    feature_df = pd.read_parquet(feat_path)
    scores = predict_scores(model, feat_cols, feature_df)
    t3 = tier3_filter(scores, feature_df, prob_cutoff=prob_cutoff)

    passed = t3[t3["tier3_pass"]].copy()
    rejected = t3[~t3["tier3_pass"]].copy()

    n_hardcheck = int(scores["hardcheck_pass"].sum())
    print(f"\n{'='*65}")
    print(f"  DAILY SHORTLIST  —  {date_str}")
    print(f"{'='*65}")
    print(f"  Universe:         {len(scores):>4} symbols")
    print(f"  Passed hardcheck: {n_hardcheck:>4} symbols")
    # Approximate historical win rate by cutoff (calibrated 2026-05-17 on 12m test data)
    _wr_map = [(0.60, 63), (0.58, 58), (0.56, 56), (0.54, 51), (0.52, 48), (0.50, 44), (0.47, 40), (0.45, 37)]
    _approx_wr = next((v for k, v in _wr_map if prob_cutoff >= k - 0.005), 30)
    print(f"  Prob cutoff:      {prob_cutoff:.2f}  (hist win rate ~{_approx_wr:.0f}%)")
    print(f"  Passed Tier 3:    {len(passed):>4} symbols  ← MUA")
    print(f"{'='*65}")

    if passed.empty:
        print("\n  Không có mã nào vượt qua tất cả tầng lọc hôm nay.")
    else:
        print(f"\n  {'Symbol':<8} {'Prob':>6} {'Score':>7} {'Rank':>6}")
        print(f"  {'-'*35}")
        for _, row in passed.iterrows():
            print(f"  {row['symbol']:<8} {row['raw_prob']:>6.3f} {int(row['score_1000']):>7} {int(row['rank']):>6}")

    if not rejected.empty:
        print(f"\n  Passed hardcheck nhưng fail Tier 3 ({len(rejected)} symbols):")
        for _, row in rejected.head(10).iterrows():
            print(f"  {row['symbol']:<8} prob={row['raw_prob']:.3f}  [{row['tier3_reasons']}]")
    print()


# ── main ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Phase 4: LightGBM propensity model")
    parser.add_argument("--check",   action="store_true", help="Show dataset stats only")
    parser.add_argument("--predict", metavar="DATE",       help="Score symbols for DATE (YYYY-MM-DD)")
    args = parser.parse_args()

    if args.check:
        show_stats()
    elif args.predict:
        run_predict(args.predict)
    else:
        run()


if __name__ == "__main__":
    main()
